#:schema node_modules/wrangler/config-schema.json
name = "finpals-telegram"
main = "src/index.ts"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

# Cloudflare account ID - set via environment variable or --account-id flag
# account_id = "your_account_id_here"

[vars]
# Environment configuration (this is production config)
ENV = "production"

# IMPORTANT: Never commit secrets to version control!
# Set these via Cloudflare dashboard or wrangler secret command:
# wrangler secret put BOT_TOKEN
# wrangler secret put TELEGRAM_BOT_API_SECRET_TOKEN
# wrangler secret put EXCHANGE_RATE_API_KEY (optional)

# For local development, use .dev.vars file (never commit this file)

# Workers Logs
[observability]
enabled = true

# Automatically place your workloads in an optimal location
[placement]
mode = "smart"

# Durable Object for grammY sessions
[durable_objects]
bindings = [
  { name = "SESSIONS", class_name = "SessionDO" }
]

[[migrations]]
tag = "0001_session_do"
new_sqlite_classes = ["SessionDO"]

# Hyperdrive configuration for CockroachDB
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "7d0cebc7c9394008a9cfdbd3e2aea5c4"
# For local development, set HYPERDRIVE_LOCAL_CONNECTION_STRING in .dev.vars