#:schema node_modules/wrangler/config-schema.json
name = "finpals-telegram"
main = "src/index.ts"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]

# Add your Cloudflare account ID here
account_id = "7a041c2905e112bf0752fd7c8e577f15"

[vars]
# These will be set as secrets in Cloudflare dashboard or via wrangler secret
# BOT_TOKEN and TELEGRAM_BOT_API_SECRET_TOKEN should be set as secrets
ENV = "development"
BOT_TOKEN="8032355908:AAGNPQVimcJi_sOnLGf5K2ZnrgWlHy4srbY"
TELEGRAM_BOT_API_SECRET_TOKEN="3C2BE62791F90E6561D4BFBBCF7242DF526BF39E0B925BE485A8FF0F1C96CB24"
# Exchange Rate API key (optional - will use mock rates if not provided)
# Get free API key from https://app.exchangerate-api.com/sign-up
# EXCHANGE_RATE_API_KEY = "your_api_key_here"

# Workers Logs
[observability]
enabled = true

# Cron trigger for recurring reminders and exchange rate updates (runs hourly)
[triggers]
crons = ["0 * * * *"]

# Automatically place your workloads in an optimal location
[placement]
mode = "smart"

# Durable Object for grammY sessions
[durable_objects]
bindings = [
  { name = "SESSIONS", class_name = "SessionDO" }
]

[[migrations]]
tag = "0001_session_do"
new_sqlite_classes = ["SessionDO"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "finpals-db"
database_id = "897f6b1e-e788-43c8-bc9a-0b499727716c"  # Replace with your database ID from dashboard

# AI binding for receipt OCR
[ai]
binding = "AI"

# Production environment
[env.production]
vars = { ENV = "production" }

[env.production.durable_objects]
bindings = [
  { name = "SESSIONS", class_name = "SessionDO" }
]

[[env.production.migrations]]
tag = "0001_session_do"
new_sqlite_classes = ["SessionDO"]

[[env.production.d1_databases]]
binding = "DB"
database_name = "finpals-db"
database_id = "897f6b1e-e788-43c8-bc9a-0b499727716c"

# Test environment
[env.test]
vars = { ENV = "test" }

[env.test.durable_objects]
bindings = [
  { name = "SESSIONS", class_name = "SessionDO" }
]

[[env.test.migrations]]
tag = "0001_session_do"
new_sqlite_classes = ["SessionDO"]

[[env.test.d1_databases]]
binding = "DB"
database_name = "finpals-db-test"
database_id = "YOUR_TEST_DATABASE_ID"